In [26]:
import pandas as pd
import sqlite3

In [27]:
df = pd.read_excel("data/g13_ridesharing.xlsx")
conn = sqlite3.connect("data/g13_ridesharing.db")

In [28]:
cars = df.loc[:, ['id_car', 'description', 'id_company', 'car_type']].copy()
cars = cars.drop_duplicates(subset='id_car', keep='first')
cars['id_car'] = cars['id_car'].astype(int)
cars['id_company'] = cars['id_company'].astype(int)
cars['car_type'] = cars['car_type'].astype(int)
cars = cars.rename(columns={'id_car': 'id'})

In [29]:
cars.to_sql("Car", conn, if_exists="append", index=False)

1199

In [30]:
pd.read_sql("SELECT * FROM Car LIMIT 20", conn)

    id  description  id_company  car_type
0    1        trade         347         1
1    2        force          60         1
2    3      subject         307         1
3    4         most         373         1
4    5      serious          68         1
5    6         hand         156         1
6    7      current         413         1
7    8  traditional         415         1
8    9        after         429         1
9   10         full         461         1
10  11     indicate          68         1
11  12          yes         220         1
12  13         lose         329         1
13  14    interview         484         1
14  15    direction         301         1
15  16      machine         301         1
16  17      against          95         1
17  18     customer         436         1
18  19        heavy         424         1
19  20      company         165         1

In [31]:
companies = df.loc[:, ['id_company', 'name', 'begin_date']].copy()
companies = companies.drop_duplicates(subset='id_company', keep='first')
companies['id_company'] = companies['id_company'].astype(int)
companies = companies.rename(columns={'id_company': 'id'})

In [32]:
companies.to_sql("Company", conn, if_exists="append", index=False)

500

In [33]:
pd.read_sql("SELECT * FROM Company LIMIT 20", conn)

    id                            name  begin_date
0    1                   Roberts-Hurst  2025-12-25
1    2       Brewer, Gregory and Kelly  2022-05-15
2    3       Pugh, Harrison and Martin  2023-03-02
3    4                   Roberts-Hicks  2025-01-22
4    5         Hahn, Allen and Lambert  2023-10-07
5    6                   Clark-Spencer  2022-08-22
6    7     Miller, Gutierrez and Stark  2022-12-23
7    8  Bradshaw, Strickland and Olson  2024-05-08
8    9                Marquez-Gonzalez  2023-05-22
9   10                 Nguyen-Williams  2024-07-21
10  11               Martinez-Thompson  2024-05-03
11  12                  Holloway-Smith  2021-11-11
12  13                   Robinson-Kemp  2024-11-23
13  14       Romero, Johnson and Lopez  2023-01-18
14  15              Williamson-Gilbert  2022-02-12
15  16                   Mayo and Sons  2022-03-09
16  17                   Norton-Watson  2021-03-13
17  18                     Escobar LLC  2024-12-22
18  19    Gutierrez, Johnson and Jones  2023-03-29
19  20                     Massey-Pace  2022-02-18

In [34]:
contracts = df.loc[:, ['id_contract', 'contract_start', 'contract_end', 'id_company', 'id_driver']].copy()
contracts = contracts.drop_duplicates(subset='id_company', keep='first')
contracts['id_contract'] = contracts['id_contract'].astype(int)
contracts['id_company'] = contracts['id_company'].astype(int)
contracts['id_driver'] = contracts['id_driver'].astype(int)
contracts = contracts.rename(columns={'id_contract': 'id'})

In [35]:
contracts.to_sql("Contract", conn, if_exists="append", index=False)

500

In [36]:
pd.read_sql("SELECT * FROM Contract LIMIT 20", conn)

    id       contract_start         contract_end  id_company  id_driver
0    1  2024-10-06 15:47:00                 None         403        762
1    2  2024-04-25 15:05:00  2026-08-21 15:05:00         348        312
2    3  2024-10-04 08:18:00  2025-05-21 08:18:00         423        641
3    4  2025-01-27 12:25:00                 None         205        444
4    5  2024-08-30 20:07:00                 None          81        789
5    6  2021-11-26 12:23:00  2024-11-03 12:23:00          85        537
6    7  2025-03-31 07:07:00                 None         149        956
7    9  2022-02-14 13:21:00  2023-11-21 13:21:00          34        771
8   10  2024-07-14 08:00:00  2025-11-29 08:00:00         407        261
9   11  2023-01-08 11:28:00                 None          88        943
10  12  2022-04-12 07:11:00                 None         320        192
11  13  2022-04-06 12:18:00                 None         207        723
12  14  2025-05-07 20:31:00                 None         347        551
13  15  2024-05-13 08:56:00  2026-11-21 08:56:00         359        903
14  16  2023-05-11 17:22:00  2024-05-07 17:22:00         383        610
15  17  2021-12-10 17:36:00                 None         322        441
16  18  2024-12-19 10:37:00                 None         362        114
17  19  2021-05-15 10:58:00                 None         282        340
18  20  2023-10-12 08:47:00                 None         315        826
19  21  2022-02-02 16:19:00                 None         426        646

In [37]:
customers = df.loc[:, ['id_customer', 'name_customer', 'email', 'phone', 'date_of_birth']].copy()
customers = customers.drop_duplicates(subset='id_customer', keep='first')
customers['id_customer'] = customers['id_customer'].astype(int)
customers['phone'] = customers['phone'].astype(int)
customers = customers.rename(columns={'id_customer': 'id'})
customers = customers.rename(columns={'name_customer': 'name'})

In [38]:
customers.to_sql("Customer", conn, if_exists="append", index=False)

40

In [39]:
pd.read_sql("SELECT * FROM Customer LIMIT 20", conn)

,id,name,email,phone,date_of_birth
0,1,Ana Costa,ana.costa896@gmail.com,900382935,1988-09-25
1,2,Ana Ferreira,ana.ferreira244@outlook.com,900077394,1978-01-13
2,3,Ana Pereira,ana.pereira86@outlook.com,900382454,1971-07-11
3,4,Ana Santos,ana.santos181@outlook.com,900095407,1999-12-02
4,5,Ana Silva,ana.silva192@gmail.com,900073015,1977-02-09
5,6,Goncalo Costa,goncalo.costa154@gmail.com,900049867,1996-06-20
6,7,Goncalo Ferreira,goncalo.ferreira385@gmail.com,900236832,1991-08-20
7,8,Goncalo Pereira,goncalo.pereira109@icloud.com,900168951,1971-07-02
8,9,Goncalo Santos,goncalo.santos239@gmail.com,900892644,1979-11-10
9,10,Goncalo Silva,goncalo.silva465@icloud.com,900133976,1994-10-21
10,11,Ines Costa,ines.costa852@icloud.com,900509648,2010-10-20
11,12,Ines Ferreira,ines.ferreira114@gmail.com,900044296,1989-05-13
12,13,Ines Pereira,ines.pereira158@icloud.com,900252235,1974-02-17
13,14,Ines Santos,ines.santos161@icloud.com,900182383,1980-10-31
14,15,Ines Silva,ines.silva102@gmail.com,900358102,1990-12-14
15,16,Joao Costa,joao.costa16@gmail.com,900181252,1995-10-21
16,17,Joao Ferreira,joao.ferreira201@gmail.com,900034900,1993-07-13
17,18,Joao Pereira,joao.pereira271@outlook.com,900364993,1986-09-06
18,19,Joao Santos,joao.santos10@icloud.com,900406029,1980-10-14
19,20,Joao Silva,joao.silva196@icloud.com,900106759,1980-01-25

In [40]:
drivers = df.loc[:, ['id_driver', 'nickname', 'driver_type']].copy()
drivers = drivers.drop_duplicates(subset='id_driver', keep='first')
drivers['id_driver'] = drivers['id_driver'].astype(int)
drivers = drivers.rename(columns={'id_driver': 'id'})

In [41]:
drivers.to_sql("Driver", conn, if_exists="append", index=False)

1000

In [42]:
pd.read_sql("SELECT * FROM Driver LIMIT 20", conn)

    id        nickname           driver_type
0    1             Can           Storyteller
1    2            Bank      Playlist Maestro
2    3          Forget   Tech-Obsessed Pilot
3    4            Foot      Speed Enthusiast
4    5         Kitchen        Snack Provider
5    6           Eight       Chill Navigator
6    7            Left             Night Owl
7    8           Quite           Clean Freak
8    9          Happen       Chill Navigator
9   10           Month            Early Bird
10  11         Thought            Early Bird
11  12  Administration  Conversation Curator
12  13    Organization      Road Philosopher
13  14           Owner           Clean Freak
14  15             And   Tech-Obsessed Pilot
15  16     Development     Shortcut Sorcerer
16  17            Draw      Playlist Maestro
17  18              It        Silent Cruiser
18  19            Make     Shortcut Sorcerer
19  20           Local     Friendly Neighbor

In [43]:
rides = df.loc[:, ['id_ride', 'id_company', 'id_driver', 'id_customer', 'id_car', 'origin', 'destination', 'ride_date', 'amount' ]].copy()
rides = rides.drop_duplicates(subset='id_ride', keep='first')
rides['id_ride'] = rides['id_ride'].astype(int)
rides['id_company'] = rides['id_company'].astype(int)
rides['id_driver'] = rides['id_driver'].astype(int)
rides['id_customer'] = rides['id_customer'].astype(int)
rides['id_car'] = rides['id_car'].astype(int)
rides['amount'] = rides['amount'].astype(int)
rides = rides.rename(columns={'id_ride': 'id'})

In [44]:
rides.to_sql("Ride", conn, if_exists="append", index=False)

10827

In [45]:
pd.read_sql("SELECT * FROM Ride LIMIT 20", conn)

,id,id_company,id_driver,id_customer,id_car,origin,destination,ride_date,amount
0,1,403,762,1,1199,Faro,Setubal,2024-11-14,2646
1,2,348,312,1,1198,Lisbon,Coimbra,2024-05-31,2834
2,3,423,641,1,1197,Aveiro,Faro,2024-11-24,1626
3,4,205,444,1,155,Braga,Aveiro,2025-03-01,2695
4,5,81,789,1,1196,Braga,Aveiro,2024-11-22,1875
5,6,85,537,1,87,Coimbra,Lisbon,2022-05-02,2133
6,7,149,956,1,1195,Coimbra,Aveiro,2025-07-27,1280
7,8,205,698,1,155,Porto,Coimbra,2025-04-07,2557
8,9,34,771,1,136,Aveiro,Guimaraes,2025-01-04,1867
9,10,407,261,1,1194,Braga,Setubal,2024-08-13,2001
10,11,88,943,1,1193,Coimbra,Faro,2023-10-18,2151
11,12,320,192,1,1192,Coimbra,Porto,2022-05-16,1927
12,13,207,723,1,1191,Guimaraes,Faro,2022-06-19,2115
13,14,347,551,1,1,Lisbon,Porto,2025-07-29,1391
14,15,359,903,1,97,Aveiro,Guimaraes,2024-06-16,1660
15,16,383,610,1,126,Coimbra,Lisbon,2024-06-20,1746
16,17,322,441,1,1190,Porto,Aveiro,2025-09-08,868
17,18,362,114,1,1189,Lisbon,Guimaraes,2025-03-24,2883
18,19,282,340,1,1188,Lisbon,Coimbra,2025-04-11,742
19,20,315,826,1,1187,Guimaraes,Aveiro,2023-12-02,2157

In [25]:
#testar codigo de novo; eliminar colunas da base de dados
cur = conn.cursor()
cur.execute("DELETE FROM Car;")
cur.execute("DELETE FROM Company;")
cur.execute("DELETE FROM Contract;")
cur.execute("DELETE FROM Customer;")
cur.execute("DELETE FROM Driver;")
cur.execute("DELETE FROM Ride;")
conn.commit()